export const rowNames = {
  occupancyCategory: "Occupancy Category",
  selectedSubcategory: "Subccategories",
    floorArea: "Floor Area (sqft)",
    height: "Hight (ft)",
    occupantNumber: "Occupant Number",
    occupiedPeriod: "Occupied Period (min)",
    supplyAir: "Supply Air (cfm)",
    outdoorAir: "Supply Air (cfm)",
    filter: "Filter Efficiency",
    hvacUV: "UVC Inactivation (%)",
    hvacTreatment: "Air Treatment CADR (cfm)",
    roomAC: "Air Cleaner CADR (cfm)",
    roomUV: "In Room UV CADR (cfm)",
    roomTreatment: "Air Treatment Device CADR (cfm)",
    maskInfector: "Mask Efficiency - Infector (%)",
    maskSus: "Mask Efficiency - Susceptible (%)",
    totalCADR: "Total CADR (cfm)",
    ASHRAE: "ASHRAE Std. 241",
    LANCET1: "LANCET - Equivalent Air Change Rate",
    LANCET2: "LANCET - Number of Occupants",
    LANCET3: "LANCET - Floor Area + Min ASHRAE",
    LANCET4: "LANCET - Secondary Attack Rate",
    IR: "Individual Risk (%)",
    AR: "Aboslute Risk (%)",
    drisk: "Risk by Distance (%)",
    distance: "Distance (ft)"

  };